# Generated by Django 5.2.3 on 2025-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="email",
        ),
        migrations.AddField(
            model_name="users",
            name="phone_number",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
