# Generated by Django 5.2.3 on 2025-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(default="demo@gmail.com", max_length=100),
            preserve_default=False,
        ),
    ]
