# Generated by Django 5.2.3 on 2025-07-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_users_phone_number_users_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.users"
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="users",
            table="main_users",
        ),
    ]
