# Generated by Django 5.2.3 on 2025-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="centroid_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="project",
            name="compass_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="project",
            name="divided_16_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="project",
            name="divided_32_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AddField(
            model_name="project",
            name="divided_8_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
