# Generated by Django 5.2.3 on 2025-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_project_centroid_image_project_compass_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="divided_16_dxf",
            field=models.FileField(blank=True, null=True, upload_to="divided_16_dxf/"),
        ),
        migrations.AddField(
            model_name="project",
            name="divided_32_dxf",
            field=models.FileField(blank=True, null=True, upload_to="divided_32_dxf/"),
        ),
        migrations.AddField(
            model_name="project",
            name="divided_8_dxf",
            field=models.FileField(blank=True, null=True, upload_to="divided_8_dxf/"),
        ),
    ]
