# Generated by Django 5.2.3 on 2026-04-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_project_divided_16_dxf_project_divided_32_dxf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VastuReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vastu_score", models.IntegerField(default=0)),
                ("overall_summary", models.TextField(blank=True)),
                ("zone_analysis", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(default=list)),
                ("positive_aspects", models.JSONField(default=list)),
                ("doshas", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vastu_report",
                        to="main.project",
                    ),
                ),
            ],
        ),
    ]
